version: "1.0"

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chat_db

  db:
    image: postgres:13
    container_name: db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=chat_db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"